const yesNoStatusOptions = [
  { value: 'active', label: 'Active' },
  { value: 'inactive', label: 'Inactive' },
]

const patientGenderOptions = [
  { value: 'Male', label: 'Male' },
  { value: 'Female', label: 'Female' },
  { value: 'Other', label: 'Other' },
]

const bloodGroupOptions = [
  { value: 'A+', label: 'A+' },
  { value: 'A-', label: 'A-' },
  { value: 'B+', label: 'B+' },
  { value: 'B-', label: 'B-' },
  { value: 'AB+', label: 'AB+' },
  { value: 'AB-', label: 'AB-' },
  { value: 'O+', label: 'O+' },
  { value: 'O-', label: 'O-' },
]

const appointmentStatusOptions = [
  { value: 'Scheduled', label: 'Scheduled' },
  { value: 'In Progress', label: 'In Progress' },
  { value: 'Completed', label: 'Completed' },
  { value: 'Cancelled', label: 'Cancelled' },
]

const appointmentTypeOptions = [
  { value: 'OPD', label: 'OPD' },
  { value: 'IPD', label: 'IPD' },
]

const labStatusOptions = [
  { value: 'Ordered', label: 'Ordered' },
  { value: 'In Progress', label: 'In Progress' },
  { value: 'Completed', label: 'Completed' },
  { value: 'Cancelled', label: 'Cancelled' },
]

const billStatusOptions = [
  { value: 'Pending', label: 'Pending' },
  { value: 'Paid', label: 'Paid' },
  { value: 'Partially Paid', label: 'Partially Paid' },
]

const paymentMethodOptions = [
  { value: 'Cash', label: 'Cash' },
  { value: 'Card', label: 'Card' },
  { value: 'UPI', label: 'UPI' },
  { value: 'Insurance', label: 'Insurance' },
  { value: 'Bank Transfer', label: 'Bank Transfer' },
]

export const addEntityConfig = {
  department: {
    title: 'Add Department',
    description: 'Create a new department entry.',
    fields: [
      { name: 'dept_name', label: 'Department Name', type: 'text', required: true },
      { name: 'location', label: 'Location', type: 'text', required: false },
      { name: 'phone', label: 'Phone', type: 'tel', required: false },
    ],
  },
  doctor: {
    title: 'Add Doctor',
    description: 'Add doctor profile and department reference.',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'specialization', label: 'Specialization', type: 'text', required: true },
      { name: 'qualification', label: 'Qualification', type: 'text', required: false },
      {
        name: 'dept_id',
        label: 'Department',
        type: 'number',
        control: 'select',
        optionsKey: 'department',
        placeholder: 'Select department',
        required: true,
      },
      { name: 'phone', label: 'Phone', type: 'tel', required: false },
      { name: 'email', label: 'Email', type: 'email', required: false },
      {
        name: 'consultation_fee',
        label: 'Consultation Fee',
        type: 'number',
        required: false,
        step: '0.01',
      },
      {
        name: 'status',
        label: 'Status',
        type: 'text',
        control: 'select',
        options: yesNoStatusOptions,
        defaultValue: 'active',
        required: true,
      },
      { name: 'available_days', label: 'Available Days', type: 'text', required: false },
    ],
  },
  patient: {
    title: 'Add Patient',
    description: 'Capture required patient details.',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'dob', label: 'Date of Birth', type: 'date', required: true },
      {
        name: 'gender',
        label: 'Gender',
        type: 'text',
        control: 'select',
        options: patientGenderOptions,
        placeholder: 'Select gender',
        required: false,
      },
      { name: 'phone', label: 'Phone', type: 'tel', required: true },
      { name: 'email', label: 'Email', type: 'email', required: false },
      { name: 'address', label: 'Address', type: 'text', control: 'textarea', required: false },
      { name: 'emergency_contact', label: 'Emergency Contact', type: 'text', required: false },
      {
        name: 'blood_group',
        label: 'Blood Group',
        type: 'text',
        control: 'select',
        options: bloodGroupOptions,
        placeholder: 'Select blood group',
        required: false,
      },
      { name: 'allergies', label: 'Allergies', type: 'text', control: 'textarea', required: false },
    ],
  },
  appointment: {
    title: 'Add Appointment',
    description: 'Schedule a patient appointment.',
    fields: [
      {
        name: 'patient_id',
        label: 'Patient',
        type: 'number',
        control: 'select',
        optionsKey: 'patient',
        placeholder: 'Select patient',
        required: true,
      },
      {
        name: 'doctor_id',
        label: 'Doctor',
        type: 'number',
        control: 'select',
        optionsKey: 'doctor',
        placeholder: 'Select doctor',
        required: true,
      },
      { name: 'appointment_date', label: 'Appointment Date', type: 'date', required: true },
      { name: 'time_slot', label: 'Time Slot', type: 'time', required: true },
      {
        name: 'status',
        label: 'Status',
        type: 'text',
        control: 'select',
        options: appointmentStatusOptions,
        defaultValue: 'Scheduled',
        required: true,
      },
      {
        name: 'type',
        label: 'Type',
        type: 'text',
        control: 'select',
        options: appointmentTypeOptions,
        defaultValue: 'OPD',
        required: true,
      },
    ],
  },
  medical_record: {
    title: 'Add Medical Record',
    description: 'Record patient visit details.',
    fields: [
      {
        name: 'patient_id',
        label: 'Patient',
        type: 'number',
        control: 'select',
        optionsKey: 'patient',
        placeholder: 'Select patient',
        required: true,
      },
      {
        name: 'doctor_id',
        label: 'Doctor',
        type: 'number',
        control: 'select',
        optionsKey: 'doctor',
        placeholder: 'Select doctor',
        required: true,
      },
      { name: 'diagnosis', label: 'Diagnosis', type: 'text', control: 'textarea', required: false },
      { name: 'treatment', label: 'Treatment', type: 'text', control: 'textarea', required: false },
      { name: 'notes', label: 'Notes', type: 'text', control: 'textarea', required: false },
      {
        name: 'record_type',
        label: 'Record Type',
        type: 'text',
        control: 'select',
        options: appointmentTypeOptions,
        defaultValue: 'OPD',
        required: true,
      },
    ],
  },
  lab_test: {
    title: 'Add Lab Test',
    description: 'Create a new lab test order.',
    fields: [
      {
        name: 'patient_id',
        label: 'Patient',
        type: 'number',
        control: 'select',
        optionsKey: 'patient',
        placeholder: 'Select patient',
        required: true,
      },
      {
        name: 'doctor_id',
        label: 'Doctor',
        type: 'number',
        control: 'select',
        optionsKey: 'doctor',
        placeholder: 'Select doctor',
        required: true,
      },
      { name: 'test_name', label: 'Test Name', type: 'text', required: true },
      {
        name: 'status',
        label: 'Status',
        type: 'text',
        control: 'select',
        options: labStatusOptions,
        defaultValue: 'Ordered',
        required: true,
      },
      { name: 'result_value', label: 'Result Value', type: 'text', control: 'textarea', required: false },
      { name: 'normal_range', label: 'Normal Range', type: 'text', required: false },
      { name: 'price', label: 'Price', type: 'number', required: false, step: '0.01' },
    ],
  },
  prescription: {
    title: 'Add Prescription',
    description: 'Create a medicine prescription.',
    fields: [
      {
        name: 'patient_id',
        label: 'Patient',
        type: 'number',
        control: 'select',
        optionsKey: 'patient',
        placeholder: 'Select patient',
        required: true,
      },
      {
        name: 'doctor_id',
        label: 'Doctor',
        type: 'number',
        control: 'select',
        optionsKey: 'doctor',
        placeholder: 'Select doctor',
        required: true,
      },
      { name: 'medicine_name', label: 'Medicine Name', type: 'text', required: true },
      { name: 'dosage', label: 'Dosage', type: 'text', required: false },
      { name: 'frequency', label: 'Frequency', type: 'text', required: false },
      { name: 'duration', label: 'Duration', type: 'text', required: false },
      { name: 'quantity', label: 'Quantity', type: 'number', required: false },
    ],
  },
  bill: {
    title: 'Add Bill',
    description: 'Create a new billing record.',
    fields: [
      {
        name: 'patient_id',
        label: 'Patient',
        type: 'number',
        control: 'select',
        optionsKey: 'patient',
        placeholder: 'Select patient',
        required: true,
      },
      { name: 'description', label: 'Description', type: 'text', control: 'textarea', required: false },
      { name: 'total_amount', label: 'Total Amount', type: 'number', required: true, step: '0.01' },
      { name: 'paid_amount', label: 'Paid Amount', type: 'number', required: false, step: '0.01' },
      {
        name: 'status',
        label: 'Status',
        type: 'text',
        control: 'select',
        options: billStatusOptions,
        defaultValue: 'Pending',
        required: true,
      },
      {
        name: 'payment_method',
        label: 'Payment Method',
        type: 'text',
        control: 'select',
        options: paymentMethodOptions,
        placeholder: 'Select payment method',
        required: false,
      },
    ],
  },
}
