export const addEntityConfig = {
  department: {
    title: 'Add Department',
    description: 'Create a new department entry.',
    fields: [
      { name: 'dept_id', label: 'Department ID', type: 'number', required: false },
      { name: 'dept_name', label: 'Department Name', type: 'text', required: true },
      { name: 'location', label: 'Location', type: 'text', required: false },
      { name: 'phone', label: 'Phone', type: 'tel', required: false },
    ],
  },
  doctor: {
    title: 'Add Doctor',
    description: 'Add doctor profile and department reference.',
    fields: [
      { name: 'doctor_id', label: 'Doctor ID', type: 'number', required: false },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'specialization', label: 'Specialization', type: 'text', required: true },
      { name: 'qualification', label: 'Qualification', type: 'text', required: false },
      { name: 'dept_id', label: 'Department ID', type: 'number', required: true },
      { name: 'phone', label: 'Phone', type: 'tel', required: false },
      { name: 'email', label: 'Email', type: 'email', required: false },
      {
        name: 'consultation_fee',
        label: 'Consultation Fee',
        type: 'number',
        required: false,
        step: '0.01',
      },
      { name: 'status', label: 'Status', type: 'text', required: false },
      { name: 'available_days', label: 'Available Days', type: 'text', required: false },
    ],
  },
  patient: {
    title: 'Add Patient',
    description: 'Capture required patient details.',
    fields: [
      { name: 'patient_id', label: 'Patient ID', type: 'number', required: false },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'dob', label: 'Date of Birth', type: 'date', required: true },
      { name: 'gender', label: 'Gender', type: 'text', required: false },
      { name: 'phone', label: 'Phone', type: 'tel', required: true },
      { name: 'email', label: 'Email', type: 'email', required: false },
      { name: 'address', label: 'Address', type: 'text', required: false },
      { name: 'emergency_contact', label: 'Emergency Contact', type: 'text', required: false },
      { name: 'blood_group', label: 'Blood Group', type: 'text', required: false },
      { name: 'allergies', label: 'Allergies', type: 'text', required: false },
      {
        name: 'registered_date',
        label: 'Registered Date',
        type: 'datetime-local',
        required: false,
      },
    ],
  },
  appointment: {
    title: 'Add Appointment',
    description: 'Schedule a patient appointment.',
    fields: [
      { name: 'appointment_id', label: 'Appointment ID', type: 'number', required: false },
      { name: 'patient_id', label: 'Patient ID', type: 'number', required: true },
      { name: 'doctor_id', label: 'Doctor ID', type: 'number', required: true },
      { name: 'appointment_date', label: 'Appointment Date', type: 'date', required: true },
      { name: 'time_slot', label: 'Time Slot', type: 'time', required: true },
      { name: 'status', label: 'Status', type: 'text', required: false },
      { name: 'type', label: 'Type', type: 'text', required: false },
      { name: 'created_at', label: 'Created At', type: 'datetime-local', required: false },
    ],
  },
  medical_record: {
    title: 'Add Medical Record',
    description: 'Record patient visit details.',
    fields: [
      { name: 'record_id', label: 'Record ID', type: 'number', required: false },
      { name: 'patient_id', label: 'Patient ID', type: 'number', required: true },
      { name: 'doctor_id', label: 'Doctor ID', type: 'number', required: true },
      { name: 'visit_date', label: 'Visit Date', type: 'datetime-local', required: false },
      { name: 'diagnosis', label: 'Diagnosis', type: 'text', required: false },
      { name: 'treatment', label: 'Treatment', type: 'text', required: false },
      { name: 'notes', label: 'Notes', type: 'text', required: false },
      { name: 'record_type', label: 'Record Type', type: 'text', required: false },
    ],
  },
  lab_test: {
    title: 'Add Lab Test',
    description: 'Create a new lab test order.',
    fields: [
      { name: 'test_id', label: 'Test ID', type: 'number', required: false },
      { name: 'patient_id', label: 'Patient ID', type: 'number', required: true },
      { name: 'doctor_id', label: 'Doctor ID', type: 'number', required: true },
      { name: 'test_name', label: 'Test Name', type: 'text', required: true },
      { name: 'order_date', label: 'Order Date', type: 'datetime-local', required: false },
      { name: 'status', label: 'Status', type: 'text', required: false },
      { name: 'result_value', label: 'Result Value', type: 'text', required: false },
      { name: 'normal_range', label: 'Normal Range', type: 'text', required: false },
      { name: 'price', label: 'Price', type: 'number', required: false, step: '0.01' },
    ],
  },
  prescription: {
    title: 'Add Prescription',
    description: 'Create a medicine prescription.',
    fields: [
      { name: 'prescription_id', label: 'Prescription ID', type: 'number', required: false },
      { name: 'patient_id', label: 'Patient ID', type: 'number', required: true },
      { name: 'doctor_id', label: 'Doctor ID', type: 'number', required: true },
      { name: 'medicine_name', label: 'Medicine Name', type: 'text', required: true },
      { name: 'dosage', label: 'Dosage', type: 'text', required: false },
      { name: 'frequency', label: 'Frequency', type: 'text', required: false },
      { name: 'duration', label: 'Duration', type: 'text', required: false },
      { name: 'quantity', label: 'Quantity', type: 'number', required: false },
      {
        name: 'prescribed_date',
        label: 'Prescribed Date',
        type: 'datetime-local',
        required: false,
      },
    ],
  },
  bill: {
    title: 'Add Bill',
    description: 'Create a new billing record.',
    fields: [
      { name: 'bill_id', label: 'Bill ID', type: 'number', required: false },
      { name: 'patient_id', label: 'Patient ID', type: 'number', required: true },
      { name: 'bill_date', label: 'Bill Date', type: 'datetime-local', required: false },
      { name: 'description', label: 'Description', type: 'text', required: false },
      { name: 'total_amount', label: 'Total Amount', type: 'number', required: true, step: '0.01' },
      { name: 'paid_amount', label: 'Paid Amount', type: 'number', required: false, step: '0.01' },
      { name: 'balance', label: 'Balance', type: 'number', required: false, step: '0.01' },
      { name: 'status', label: 'Status', type: 'text', required: false },
      { name: 'payment_method', label: 'Payment Method', type: 'text', required: false },
    ],
  },
}
